# Install script for directory: /Users/jaeseoko/Research/public/src

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/jaeseoko/Research/build_ysgebl2/ysclass/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysclass11/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysport/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgl/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysglcpp/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysglcpp/src/gl2/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysglcpp/src/gl1/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysglcpp/src/nownd/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysbitmap/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysbitmap/cmdtools/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysbitmaputil/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysbitmapfont/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysbitmapfont/cmdtools/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/yssystemfont/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fssimplewindow/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fssimplewindow/template/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fssimplewindow/samples/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/yssimplesound/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/yssimplesound/test/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/yssimplesound/sample/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/yssimplesound/sample_fssimplewindow/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fslazywindow/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fslazywindow/template/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fslazywindow/samples/sample00-bouncingBall/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fssimplefiledialog/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fssimplefiledialog/sample/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysfontrenderer/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ystexturemanager/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ystexturemanager/src/gl/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ystexturemanager/src/null/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsguilib/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsguilib/src/gl2/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsguilib/src/gl1/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsguilib/src/nownd/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsguilib/filedialog/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsguilib/template/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsguilib/template_with_filedialog/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsgui3d/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsgui3d/src/gl1/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsgui3d/src/gl2/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsgui3d/template/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsgui3d/template_with_filedialog/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/fsgui3d/template-easy/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/yssocket/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/kernel/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/kernelutil/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/shellrender/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/shellrender/gl2/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/shellrender/gl1/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/shellrender/nownd/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/gui_foundation/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/gui/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/main/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/cmdlib/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/cmdmain/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ysgebl/src/samples/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/2DRetroMapTool/src/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/ir_transceiver/cmake_install.cmake")
  include("/Users/jaeseoko/Research/build_ysgebl2/opencv/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/Users/jaeseoko/Research/build_ysgebl2/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
